# Generated by Django 5.0.7 on 2024-08-05 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_coffeechats', to=settings.AUTH_USER_MODEL)),
                ('hashtags', models.ManyToManyField(related_name='coffeechats', to='coffeechat.hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', '수락대기중'), ('ACCEPTED', '수락'), ('LIMITED', '최대요청횟수초과'), ('PRIVATE', '비공개')], default='WAITING', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coffeechat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='coffeechat.coffeechat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coffeechat_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='coffeechat.coffeechatrequest')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffeechat_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
