# Generated by Django 5.0.7 on 2024-08-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeechat',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
