# Generated by Django 5.0.7 on 2024-08-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeechatrequest',
            name='status',
            field=models.CharField(choices=[('WAITING', '수락대기중'), ('ACCEPTED', '수락'), ('LIMITED', '최대요청횟수초과'), ('PRIVATE', '비공개'), ('REJECTED', '거절')], default='WAITING', max_length=10),
        ),
    ]
