# Generated by Django 5.0.7 on 2024-08-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeechat', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='content',
        ),
    ]
