# Generated by Django 5.1 on 2024-08-16 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coffeechat", "0002_coffeechat_is_public"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coffeechatrequest",
            old_name="user",
            new_name="sender",
        ),
    ]
