# Generated by Django 5.1 on 2024-08-16 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coffeechat", "0003_rename_user_coffeechatrequest_sender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coffeechatrequest",
            old_name="sender",
            new_name="user",
        ),
    ]
