# Generated by Django 5.1 on 2024-08-17 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeechat', '0003_rename_user_coffeechatrequest_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeechatrequest',
            old_name='sender',
            new_name='user',
        ),
        migrations.AddField(
            model_name='coffeechat',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_coffeechats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coffeechat',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_coffeechats', to=settings.AUTH_USER_MODEL),
        ),
    ]
