# Generated by Django 5.0.7 on 2024-08-04 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='corboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cor_comments', to='corboard.corboard'),
        ),
        migrations.AlterField(
            model_name='corboard',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='cor_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corboard',
            name='corboardImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='corboard',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='cor_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
