# Generated by Django 5.0.7 on 2024-08-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=1, help_text='전화번호를 입력하세요.', max_length=15, verbose_name='전화번호'),
            preserve_default=False,
        ),
    ]
