# Generated by Django 5.0.7 on 2024-08-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cohort',
            field=models.IntegerField(blank=True, help_text='몇기인지 입력하세요.', null=True),
        ),
    ]
