# Generated by Django 5.0.7 on 2024-08-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_cohort"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="intro",
            field=models.TextField(blank=True, null=True, verbose_name="소개"),
        ),
    ]
