# Generated by Django 5.0.7 on 2024-08-02 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeechat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeechat',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coffeechat',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_coffeechats', to=settings.AUTH_USER_MODEL),
        ),
    ]
