# Generated by Django 5.0.7 on 2024-08-03 13:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeechat', '0002_alter_coffeechat_count_alter_coffeechat_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeechat',
            name='status',
        ),
        migrations.RemoveField(
            model_name='coffeechat',
            name='username',
        ),
        migrations.CreateModel(
            name='CoffeeChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', '수락대기중'), ('ACCEPTED', '수락'), ('LIMITED', '최대요청횟수초과'), ('PRIVATE', '비공개')], default='WAITING', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coffeechat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='coffeechat.coffeechat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
